/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author fernando
 */
public class Interfaz extends javax.swing.JFrame {
    
    protected static Calculadora cal;
    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respuestaTF = new javax.swing.JTextField();
        pAbiertoBT = new javax.swing.JButton();
        pCerradoBT = new javax.swing.JButton();
        dividirBT = new javax.swing.JButton();
        sieteBT = new javax.swing.JButton();
        ochoBT = new javax.swing.JButton();
        nueveBT = new javax.swing.JButton();
        multiplicaBT = new javax.swing.JButton();
        cuatroBT = new javax.swing.JButton();
        cincoBT = new javax.swing.JButton();
        seisBT = new javax.swing.JButton();
        menosBT = new javax.swing.JButton();
        unoBT = new javax.swing.JButton();
        dosBT = new javax.swing.JButton();
        tresBT = new javax.swing.JButton();
        masBT = new javax.swing.JButton();
        ceroBT = new javax.swing.JButton();
        signoBT = new javax.swing.JButton();
        igualBT = new javax.swing.JButton();
        puntoBT = new javax.swing.JButton();
        cBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        respuestaTF.setEditable(false);
        respuestaTF.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        respuestaTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        respuestaTF.setMinimumSize(new java.awt.Dimension(50, 280));
        respuestaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaTFActionPerformed(evt);
            }
        });

        pAbiertoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        pAbiertoBT.setText("(");
        pAbiertoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAbiertoBTActionPerformed(evt);
            }
        });

        pCerradoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        pCerradoBT.setText(")");
        pCerradoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCerradoBTActionPerformed(evt);
            }
        });

        dividirBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dividirBT.setText("÷");
        dividirBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirBTActionPerformed(evt);
            }
        });

        sieteBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        sieteBT.setText("7");
        sieteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteBTActionPerformed(evt);
            }
        });

        ochoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ochoBT.setText("8");
        ochoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBTActionPerformed(evt);
            }
        });

        nueveBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nueveBT.setText("9");
        nueveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveBTActionPerformed(evt);
            }
        });

        multiplicaBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        multiplicaBT.setText("x");
        multiplicaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaBTActionPerformed(evt);
            }
        });

        cuatroBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cuatroBT.setText("4");
        cuatroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroBTActionPerformed(evt);
            }
        });

        cincoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cincoBT.setText("5");
        cincoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBTActionPerformed(evt);
            }
        });

        seisBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        seisBT.setText("6");
        seisBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBTActionPerformed(evt);
            }
        });

        menosBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        menosBT.setText("-");
        menosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosBTActionPerformed(evt);
            }
        });

        unoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        unoBT.setText("1");
        unoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBTActionPerformed(evt);
            }
        });

        dosBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dosBT.setText("2");
        dosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBTActionPerformed(evt);
            }
        });

        tresBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tresBT.setText("3");
        tresBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBTActionPerformed(evt);
            }
        });

        masBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        masBT.setText("+");
        masBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masBTActionPerformed(evt);
            }
        });

        ceroBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ceroBT.setText("0");
        ceroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroBTActionPerformed(evt);
            }
        });

        signoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        signoBT.setText("+/-");
        signoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoBTActionPerformed(evt);
            }
        });

        igualBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        igualBT.setText("=");
        igualBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBTActionPerformed(evt);
            }
        });

        puntoBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        puntoBT.setText(".");
        puntoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoBTActionPerformed(evt);
            }
        });

        cBT.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cBT.setText("C");
        cBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(sieteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ochoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nueveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(multiplicaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cuatroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cincoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seisBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(menosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(unoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tresBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(masBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(signoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ceroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(puntoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(igualBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pAbiertoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pCerradoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dividirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(respuestaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(respuestaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAbiertoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCerradoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sieteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ochoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igualBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pAbiertoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAbiertoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "( ");
    }//GEN-LAST:event_pAbiertoBTActionPerformed

    private void respuestaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaTFActionPerformed

    private void pCerradoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCerradoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + " )");
    }//GEN-LAST:event_pCerradoBTActionPerformed

    private void dividirBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + " / ");
    }//GEN-LAST:event_dividirBTActionPerformed

    private void sieteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteBTActionPerformed
      respuestaTF.setText(respuestaTF.getText() + "7");
    }//GEN-LAST:event_sieteBTActionPerformed

    private void ochoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "8");
    }//GEN-LAST:event_ochoBTActionPerformed

    private void nueveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "9");
    }//GEN-LAST:event_nueveBTActionPerformed

    private void multiplicaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + " x ");
    }//GEN-LAST:event_multiplicaBTActionPerformed

    private void cuatroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "4");
    }//GEN-LAST:event_cuatroBTActionPerformed

    private void cincoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "5");
    }//GEN-LAST:event_cincoBTActionPerformed

    private void seisBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "6");
    }//GEN-LAST:event_seisBTActionPerformed

    private void menosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + " - ");
    }//GEN-LAST:event_menosBTActionPerformed

    private void unoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "1");
    }//GEN-LAST:event_unoBTActionPerformed

    private void dosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "2");
    }//GEN-LAST:event_dosBTActionPerformed

    private void tresBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "3");
    }//GEN-LAST:event_tresBTActionPerformed

    private void masBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + " + ");
    }//GEN-LAST:event_masBTActionPerformed

    private void ceroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "0");
    }//GEN-LAST:event_ceroBTActionPerformed

    private void signoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + "-");
    }//GEN-LAST:event_signoBTActionPerformed

    private void igualBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBTActionPerformed
        double res = 0;
        cal = new Calculadora (respuestaTF.getText());
        
        res = cal.resuelveExpresion(cal.expresionCalculadora());
        
        respuestaTF.setText(String.valueOf(res));
    }//GEN-LAST:event_igualBTActionPerformed

    private void puntoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoBTActionPerformed
        respuestaTF.setText(respuestaTF.getText() + ".");
    }//GEN-LAST:event_puntoBTActionPerformed

    private void cBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBTActionPerformed
        respuestaTF.setText("");
        tieneMenos = false;
    }//GEN-LAST:event_cBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
   private boolean tieneMenos = false;
   private String textoTF;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBT;
    private javax.swing.JButton ceroBT;
    private javax.swing.JButton cincoBT;
    private javax.swing.JButton cuatroBT;
    private javax.swing.JButton dividirBT;
    private javax.swing.JButton dosBT;
    private javax.swing.JButton igualBT;
    private javax.swing.JButton masBT;
    private javax.swing.JButton menosBT;
    private javax.swing.JButton multiplicaBT;
    private javax.swing.JButton nueveBT;
    private javax.swing.JButton ochoBT;
    private javax.swing.JButton pAbiertoBT;
    private javax.swing.JButton pCerradoBT;
    private javax.swing.JButton puntoBT;
    private javax.swing.JTextField respuestaTF;
    private javax.swing.JButton seisBT;
    private javax.swing.JButton sieteBT;
    private javax.swing.JButton signoBT;
    private javax.swing.JButton tresBT;
    private javax.swing.JButton unoBT;
    // End of variables declaration//GEN-END:variables
}
